/*
 *  
 * Copyright 2016 Leon Bebbington Licensed under the * 	
 * 	Educational Community License, Version 2.0 (the "License"); you may * 	
 * 	not use this file except in compliance with the License. You may * 	
 * 	obtain a copy of the License at * 	
 * 	 * 	
 * 	http://www.osedu.org/licenses/ECL-2.0 * 	
 * 
 * 	Unless required by applicable law or agreed to in writing, * 	
 * 	software distributed under the License is distributed on an "AS IS" * 	
 * 	BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express * 	
 * 	or implied. See the License for the specific language governing * 	
 * 	permissions and limitations under the License. * 	
 */
package kantine_pi.aufladesystem;

import java.time.Clock;
import javax.swing.SwingUtilities;

/**
 *
 * @author Leon Bebbington
 */
public class AufladeSystemGUI extends javax.swing.JPanel {

    private final AufladeModell model;

    /**
     * Creates new form KasseGUI
     */
    public AufladeSystemGUI(AufladeModell model) {
        this.model = model;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel_Guthaben = new javax.swing.JLabel();
        jPanel_AufladeBetrag = new javax.swing.JPanel();
        jLabel_AufladeBetrag = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton_Leeren = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_KartenID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jText_Name = new javax.swing.JTextField();
        jText_Klasse = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton_Auszahlen = new javax.swing.JButton();
        jButton_Löschen = new javax.swing.JButton();
        jButton_Bearbeiten = new javax.swing.JButton();
        jButton_Aufladen = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton_KarteLesen = new javax.swing.JButton();
        jLabelVorgangStatus = new javax.swing.JLabel();
        jButton_Abbrechen = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guthaben", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setName("Guthaben"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel_Guthaben.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel_Guthaben.setText("00,00 €");
        jPanel1.add(jLabel_Guthaben, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel1, gridBagConstraints);

        jPanel_AufladeBetrag.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Auflade Betrag", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel_AufladeBetrag.setName("Guthaben"); // NOI18N
        jPanel_AufladeBetrag.setLayout(new java.awt.GridBagLayout());

        jLabel_AufladeBetrag.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel_AufladeBetrag.setText("00,00 €");
        jLabel_AufladeBetrag.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel_AufladeBetrag.setMaximumSize(new java.awt.Dimension(170, 41));
        jLabel_AufladeBetrag.setPreferredSize(new java.awt.Dimension(170, 41));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel_AufladeBetrag.add(jLabel_AufladeBetrag, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel_AufladeBetrag, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aufladen mit ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("5 €");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("10 €");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jButton2, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("25 €");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jButton3, gridBagConstraints);

        jButton_Leeren.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Leeren.setText("Leeren");
        jButton_Leeren.setToolTipText("");
        jButton_Leeren.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Leeren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LeerenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jButton_Leeren, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("50 €");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jButton4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Karten Daten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabel_KartenID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_KartenID.setText("567");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel_KartenID, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel5, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Klasse:");
        jLabel7.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel7, gridBagConstraints);

        jText_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jText_Name.setText("Leon Bebbington");
        jText_Name.setEnabled(false);
        jText_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_NameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jText_Name, gridBagConstraints);

        jText_Klasse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jText_Klasse.setText("12/3");
        jText_Klasse.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jText_Klasse, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sonderfunktionen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jButton_Auszahlen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Auszahlen.setText("Auszahlen");
        jButton_Auszahlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AuszahlenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        jPanel5.add(jButton_Auszahlen, gridBagConstraints);

        jButton_Löschen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Löschen.setText("Karte löschen");
        jButton_Löschen.setToolTipText("");
        jButton_Löschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LöschenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        jPanel5.add(jButton_Löschen, gridBagConstraints);

        jButton_Bearbeiten.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Bearbeiten.setText("Bearbeiten");
        jButton_Bearbeiten.setToolTipText("");
        jButton_Bearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BearbeitenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        jPanel5.add(jButton_Bearbeiten, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel5, gridBagConstraints);

        jButton_Aufladen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Aufladen.setText("Aufladen");
        jButton_Aufladen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AufladenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jButton_Aufladen, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kantine_pi/aufladesystem/Logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel6.add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel6, gridBagConstraints);

        jButton_KarteLesen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_KarteLesen.setText("Karte lesen");
        jButton_KarteLesen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KarteLesenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(9, 19, 1, 19);
        add(jButton_KarteLesen, gridBagConstraints);

        jLabelVorgangStatus.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelVorgangStatus.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabelVorgangStatus, gridBagConstraints);

        jButton_Abbrechen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Abbrechen.setText("Vorgang abbrechen");
        jButton_Abbrechen.setToolTipText("");
        jButton_Abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbbrechenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.insets = new java.awt.Insets(9, 19, 1, 19);
        add(jButton_Abbrechen, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jText_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (model != null) {
            model.betragaufladen(5);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (model != null) {
            model.betragaufladen(10);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (model != null) {
            model.betragaufladen(25);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_LeerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LeerenActionPerformed
        if (model != null) {
            model.betragaufladen(0);
        }
    }//GEN-LAST:event_jButton_LeerenActionPerformed

    private void jButton_BearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BearbeitenActionPerformed

        if (model != null) {
            if (jButton_Bearbeiten.getText().equalsIgnoreCase("Bearbeiten")) {
                model.bearbeiten();
            } else {
                model.bearbeiten_speichern(jText_Name.getText(), jText_Klasse.getText());
            }

        }
    }//GEN-LAST:event_jButton_BearbeitenActionPerformed

    private void jButton_KarteLesenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KarteLesenActionPerformed
        if (model != null) {
            model.karteLesen();
        }
    }//GEN-LAST:event_jButton_KarteLesenActionPerformed

    private void jButton_AuszahlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AuszahlenActionPerformed
        if (model != null) {
            model.auszahlen();
        }
    }//GEN-LAST:event_jButton_AuszahlenActionPerformed

    private void jButton_AbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbbrechenActionPerformed
        if (model != null) {
            model.abbrechen();
        }

    }//GEN-LAST:event_jButton_AbbrechenActionPerformed

    private void jButton_LöschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LöschenActionPerformed
        if (model != null) {
            model.löschen();
        }
           }//GEN-LAST:event_jButton_LöschenActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     if (model != null) {
            model.betragaufladen(50);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_AufladenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AufladenActionPerformed
      if (model != null) {
            model.aufladen();
        }
    }//GEN-LAST:event_jButton_AufladenActionPerformed

    public void setButtonZustand(final ButtonZustand bz) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {

                jButton_KarteLesen.setEnabled(bz.KarteLesenEnabled);

                jButton_Auszahlen.setEnabled(bz.AuszahlenEnabled);
                jButton_Löschen.setEnabled(bz.KarteLöschenEnabled);
                jButton_Bearbeiten.setEnabled(bz.BearbeitenEnabled);
                jButton_Abbrechen.setEnabled(bz.VorgangAbbrechenEnabled);

                jText_Name.setEnabled(bz.BearbeitenAktiv);
                jText_Klasse.setEnabled(bz.BearbeitenAktiv);

                if (bz.BearbeitenAktiv) {

                    jButton_Bearbeiten.setText("Speichern");

                } else {
                    jButton_Bearbeiten.setText("Bearbeiten");
                }

                jButton_Aufladen.setEnabled(bz.AufladeGruppeEnabled);
                jButton1.setEnabled(bz.AufladeGruppeEnabled);
                jButton2.setEnabled(bz.AufladeGruppeEnabled);
                jButton3.setEnabled(bz.AufladeGruppeEnabled);
                jButton4.setEnabled(bz.AufladeGruppeEnabled);
                jButton_Leeren.setEnabled(bz.AufladeGruppeEnabled);
            }
        });
    }

    public void setGuthaben(final String name) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jLabel_Guthaben.setText(name);
            }
        });
    }

      public void setAufladeBetrag(final String name) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jLabel_AufladeBetrag.setText(name);
            }
        });
    }
    
    public void setKarteName(final String name) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jText_Name.setText(name);
            }
        });
    }

    public void setKlasse(final String klasse) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jText_Klasse.setText(klasse);
            }
        });
    }

    public void setKartenID(final String id) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jLabel_KartenID.setText(id);
            }
        });
    }

    void setStatus(final String status) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jLabelVorgangStatus.setText(status);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels = javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx = 0; idx < installedLookAndFeels.length; idx++) {
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AufladeSystemGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AufladeSystemGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AufladeSystemGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AufladeSystemGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private AufladeSystemGUI gui;

            public void run() {
                javax.swing.JFrame frame = new javax.swing.JFrame("AufladeSystemGUI");
                frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                AufladeModell model = new AufladeModell(args[0]);
                gui = new AufladeSystemGUI(model);
                model.setGUI(gui);
                frame.getContentPane().add(gui);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Abbrechen;
    private javax.swing.JButton jButton_Aufladen;
    private javax.swing.JButton jButton_Auszahlen;
    private javax.swing.JButton jButton_Bearbeiten;
    private javax.swing.JButton jButton_KarteLesen;
    private javax.swing.JButton jButton_Leeren;
    private javax.swing.JButton jButton_Löschen;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelVorgangStatus;
    private javax.swing.JLabel jLabel_AufladeBetrag;
    private javax.swing.JLabel jLabel_Guthaben;
    private javax.swing.JLabel jLabel_KartenID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_AufladeBetrag;
    private javax.swing.JTextField jText_Klasse;
    private javax.swing.JTextField jText_Name;
    // End of variables declaration//GEN-END:variables

}
